# Generated by Django 5.2.1 on 2025-06-01 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('total_cpu', models.CharField(blank=True, max_length=100)),
                ('total_ram', models.CharField(blank=True, max_length=50)),
                ('hyperv_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=50)),
                ('disk', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HyperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HyperLink_created_by', to=settings.AUTH_USER_MODEL)),
                ('servers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HyperLink', to='core.server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='update_logs/')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.server')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], max_length=20)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.server')),
            ],
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('hyperlink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificate', to='core.hyperlink')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vm_id', models.CharField(blank=True, max_length=100)),
                ('guest_os', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], max_length=20)),
                ('assigned_cpu', models.CharField(blank=True, max_length=100)),
                ('assigned_ram', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='core.host')),
            ],
        ),
    ]
