# Generated by Django 5.2.1 on 2025-07-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlink',
            name='servers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='core.server'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
