# Generated by Django 5.2.1 on 2025-05-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('total_cpu', models.CharField(blank=True, max_length=100)),
                ('total_ram', models.CharField(blank=True, max_length=50)),
                ('hyperv_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vm_id', models.CharField(blank=True, max_length=100)),
                ('guest_os', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], max_length=20)),
                ('assigned_cpu', models.CharField(blank=True, max_length=100)),
                ('assigned_ram', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='core.host')),
            ],
        ),
    ]
