# Generated by Django 5.2.1 on 2025-05-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_remove_user_department_user_departments'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='accounts.department'),
        ),
    ]
