# Generated by Django 5.2.1 on 2025-05-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_host_virtualmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('hyperlink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificate', to='core.hyperlink')),
            ],
        ),
    ]
